import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body
        className={`bg-[#f6f6f6] regular text-[#0D2159] antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
